---
openapi: 3.0.3
#swagger: "2.0"
info:
  title: GameCookerSwagger
  description: GameCookerSwagger
  version: 1.0.0
tags:
- name: "game"
  description: "Deal with game requests"
- name: "helper"
  description: "Help to find your game"
- name: "user"
  description: "Operations about user"
- name: "admin"
  description: "Admin actions"
schemes:
- "http"
paths:
  /catalog:
    get:
      tags:
      - "game"
      summary: "Get all available games"
      description: ""
      operationId: "get_game"
      responses:
        "200":
          description: "Games are loaded"
        "405":
          description: "Invalid input"
  /pass-change/{id}:
    put:
      tags:
        - "user"
      summary: "Change password if forgot"
      description: ""
      operationId: "changePassword"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "path"
          name: "path"
          description: "List of user object"
          required: true
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
      responses:
        default:
          description: "successful operation"
definitions:
  Game:
    type: "object"
    properties:
      id:
        type: "integer"
#        format: "int64"
      name:
        type: "string"
#        format: "int64"
      players_count:
        type: "integer"
#        format: "int32"
      price:
        type: "integer"
#        format: "date-time"
      rating:
        type: "integer"
        description: "Math.avg(rating_of_users)"
      preview_url:
        type: "string"
    xml:
      name: "Game"

